### ISSUE TITLE
Using SVG Vexflow backend

### ISSUE THREAD

**Issue by freetomik** [ringw/vexflow#14]
Hi @ringw ,

is there some posibility to get your project working with using Vex.Flow.Renderer.Backends.SVG?
I read this your [comment](http://ringwa.lt/projects/musicxml/#comment-391) on similar question(that guy wanted to use Raphael, but this backend is deprecated now in Vexflow), but it's pretty old.
Could you, please, provide some advices how to do it?

Thank you!

**Comment by yodahuang** [comment]
Hi @freetomik ,

This might be late but I just made a fork of this project that adds support for both canvas and SVG.

You can see it [here](https://github.com/yodahuang/vexflow-musicxml)

Best regards

**Comment by freetomik** [comment]
Hi @yodahuang ,

It is late, but thanks for information anyway. It is good to render notes also to SVG in this project, good job.

Rendering notes to SVG is better especially for interactivity reasons. I have made basic MusicXML editor using also SVG, you can see [here](https://github.com/SymphoniaIO/web-musicxml-editor)

Best wishes
