### ISSUE TITLE
Support for double whole (aka breve) note

### ISSUE THREAD

**Issue by samaxes** [ringw/vexflow#3]
Please add support for breve note and rest.
The initial discussion can be found on the [VexFlow repo](https://github.com/0xfe/vexflow/issues/297).

**Comment by ringw** [comment]
I've applied @gristow's change (and added the other less common MusicXML durations just to be safe), and it seems to fix the issue in the viewer. Try saving your example to `tests/resources/breve_note.xml`, then open `file:///.../tests/viewer.html?doc=breve_note.xml` (Firefox works best for me). I see a breve note. I'm not sure why you got a half note before. Please let me know if it's not working for you.

**Comment by samaxes** [comment]
Thanks @ringw. I see a breve note as well.
I was probably using an older example of yours which was not working with @gristow's change.
Are you planing to create a Bower repo for the release files or can I create one?

**Comment by samaxes** [comment]
@ringw, I've created a Bower repo for your fork at samaxes/vexflow-musicxml.
