### ISSUE TITLE
Move MusicXML support into a separate package (not a fork)?

### ISSUE THREAD

**Issue by nickolay** [ringw/vexflow#9]
Have you seen https://github.com/mechanicalscribe/vexflow-musicxml ? It packages your MusicXML work separately from the base vexflow.

Apart from reducing the branch-syncing hassle, it also makes it possible to include a MusicXML-specific README and a demo, and makes it clear that MusicXML support is actually separate code building on vexflow, not a true fork. I think this makes it more approachable for possible contributors.

Would you consider switching the canonical repository from being a fork of vexflow to being a separate package depending on it?

For the reference, the repo I mentioned is behind the canonical code at the moment - and also adds some local changes, - so the following two commits are "synced":
- mechanicalscribe/vexflow-musicxml@fe7c2a58affdca9c90719176de458f4c82408a3b    Date: 21 Feb 2015 22:27:33 GMT+3    adding built files
- ringw/vexflow@15c26c6cea8311a4f7ed44d9e38ca38d7c400445    Date: 25 Jul 2014 04:51:04 GMT+4    Merge pull request #2 from aarmea/document-formatter-typo

It also doesn't include the tests and added samples.

**Comment by ringw** [comment]
Thanks. I really like this layout, and I've merged it. I'll mention @wilson428 too, hopefully he sees this.

**Comment by wilson428** [comment]
Thank you both!
